/**
 * Program IDs and IDL stubs for the SSS programs.
 *
 * In production, the IDL is fetched from the on-chain IDL account or bundled
 * at build time via `anchor build`. The stubs below are the minimum required
 * for the SDK to construct transactions; full IDL is in target/idl/.
 */

import { PublicKey } from "@solana/web3.js";

/** SSS-Token program ID. */
export const SSS_TOKEN_PROGRAM_ID = new PublicKey(
  "Gx4YCpm4DhBwDaqZya9QY2ydTP6hVa3ffPSdViPJ45x8"
);

/** Transfer-Hook program ID. */
export const TRANSFER_HOOK_PROGRAM_ID = new PublicKey(
  "9chamxxgkipFSo3VV53sNnLFRk14oJTrKFzRaHRgowfN"
);

/**
 * Minimal IDL stub for sss-token.
 *
 * Full IDL is generated by `anchor build` in target/idl/sss_token.json.
 * The SDK loads the full IDL at runtime when available; this stub allows
 * the package to be imported without a built IDL file.
 */
export const SSS_TOKEN_IDL = {
  address: "Gx4YCpm4DhBwDaqZya9QY2ydTP6hVa3ffPSdViPJ45x8",
  version: "0.1.0",
  name: "sss_token",
  instructions: [
    {
      name: "initialize",
      accounts: [
        { name: "payer", isMut: true, isSigner: true },
        { name: "masterAuthority", isMut: false, isSigner: true },
        { name: "mint", isMut: true, isSigner: true },
        { name: "globalState", isMut: true, isSigner: false },
        { name: "roleRegistry", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
        { name: "rent", isMut: false, isSigner: false },
      ],
      args: [
        {
          name: "params",
          type: {
            defined: "InitializeParams",
          },
        },
      ],
    },
    {
      name: "mint",
      accounts: [
        { name: "minter", isMut: false, isSigner: true },
        { name: "globalState", isMut: true, isSigner: false },
        { name: "minterState", isMut: true, isSigner: false },
        { name: "mint", isMut: true, isSigner: false },
        { name: "recipientTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "burn",
      accounts: [
        { name: "burner", isMut: false, isSigner: true },
        { name: "globalState", isMut: false, isSigner: false },
        { name: "roleRegistry", isMut: false, isSigner: false },
        { name: "mint", isMut: true, isSigner: false },
        { name: "burnerTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "freezeAccount",
      accounts: [
        { name: "authority", isMut: false, isSigner: true },
        { name: "globalState", isMut: false, isSigner: false },
        { name: "roleRegistry", isMut: false, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "targetTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "thawAccount",
      accounts: [
        { name: "authority", isMut: false, isSigner: true },
        { name: "globalState", isMut: false, isSigner: false },
        { name: "roleRegistry", isMut: false, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "targetTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "pause",
      accounts: [
        { name: "authority", isMut: false, isSigner: true },
        { name: "globalState", isMut: true, isSigner: false },
        { name: "roleRegistry", isMut: false, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "unpause",
      accounts: [
        { name: "authority", isMut: false, isSigner: true },
        { name: "globalState", isMut: true, isSigner: false },
        { name: "roleRegistry", isMut: false, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "updateMinter",
      accounts: [
        { name: "masterAuthority", isMut: false, isSigner: true },
        { name: "globalState", isMut: false, isSigner: false },
        { name: "minter", isMut: false, isSigner: false },
        { name: "minterState", isMut: true, isSigner: false },
        { name: "payer", isMut: true, isSigner: true },
        { name: "mint", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "newQuota", type: "u64" },
        { name: "epochDuration", type: { option: "i64" } },
      ],
    },
    {
      name: "updateRoles",
      accounts: [
        { name: "masterAuthority", isMut: false, isSigner: true },
        { name: "globalState", isMut: false, isSigner: false },
        { name: "roleRegistry", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
      ],
      args: [
        { name: "roleType", type: "string" },
        { name: "newKey", type: { option: "publicKey" } },
      ],
    },
    {
      name: "proposeAuthorityTransfer",
      accounts: [
        { name: "masterAuthority", isMut: false, isSigner: true },
        { name: "globalState", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
      ],
      args: [{ name: "newAuthority", type: "publicKey" }],
    },
    {
      name: "acceptAuthorityTransfer",
      accounts: [
        { name: "newAuthority", isMut: false, isSigner: true },
        { name: "globalState", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "addToBlacklist",
      accounts: [
        { name: "blacklister", isMut: false, isSigner: true },
        { name: "payer", isMut: true, isSigner: true },
        { name: "globalState", isMut: false, isSigner: false },
        { name: "roleRegistry", isMut: false, isSigner: false },
        { name: "blacklistEntry", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "address", type: "publicKey" },
        { name: "reason", type: "string" },
      ],
    },
    {
      name: "removeFromBlacklist",
      accounts: [
        { name: "blacklister", isMut: false, isSigner: true },
        { name: "payer", isMut: true, isSigner: true },
        { name: "globalState", isMut: false, isSigner: false },
        { name: "roleRegistry", isMut: false, isSigner: false },
        { name: "blacklistEntry", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
      ],
      args: [{ name: "address", type: "publicKey" }],
    },
    {
      name: "seize",
      accounts: [
        { name: "seizer", isMut: false, isSigner: true },
        { name: "globalState", isMut: false, isSigner: false },
        { name: "roleRegistry", isMut: false, isSigner: false },
        { name: "mint", isMut: true, isSigner: false },
        { name: "sourceTokenAccount", isMut: true, isSigner: false },
        { name: "destinationTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
  ],
  accounts: [
    {
      name: "GlobalState",
      type: {
        kind: "struct",
        fields: [
          { name: "masterAuthority", type: "publicKey" },
          { name: "mint", type: "publicKey" },
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "uri", type: "string" },
          { name: "decimals", type: "u8" },
          { name: "enablePermanentDelegate", type: "bool" },
          { name: "enableTransferHook", type: "bool" },
          { name: "defaultAccountFrozen", type: "bool" },
          { name: "isPaused", type: "bool" },
          { name: "pendingAuthority", type: { option: "publicKey" } },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "RoleRegistry",
      type: {
        kind: "struct",
        fields: [
          { name: "mint", type: "publicKey" },
          { name: "pauser", type: { option: "publicKey" } },
          { name: "burner", type: { option: "publicKey" } },
          { name: "blacklister", type: { option: "publicKey" } },
          { name: "seizer", type: { option: "publicKey" } },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "MinterState",
      type: {
        kind: "struct",
        fields: [
          { name: "mint", type: "publicKey" },
          { name: "minter", type: "publicKey" },
          { name: "maxQuota", type: "u64" },
          { name: "mintedThisEpoch", type: "u64" },
          { name: "epochStart", type: "i64" },
          { name: "epochDuration", type: "i64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "BlacklistEntry",
      type: {
        kind: "struct",
        fields: [
          { name: "mint", type: "publicKey" },
          { name: "address", type: "publicKey" },
          { name: "reason", type: "string" },
          { name: "timestamp", type: "i64" },
          { name: "by", type: "publicKey" },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: "Unauthorized", msg: "Caller does not hold the required role" },
    { code: 6001, name: "Paused", msg: "Token is currently paused" },
    { code: 6002, name: "QuotaExceeded", msg: "Minter quota exceeded for this epoch" },
    { code: 6003, name: "FeatureNotEnabled", msg: "This feature was not enabled at mint creation" },
    { code: 6004, name: "StringTooLong", msg: "String exceeds maximum allowed length" },
    { code: 6005, name: "AlreadyBlacklisted", msg: "Address is already blacklisted" },
    { code: 6006, name: "NotBlacklisted", msg: "Address is not on the blacklist" },
    { code: 6007, name: "Overflow", msg: "Arithmetic overflow" },
    { code: 6008, name: "PendingTransfer", msg: "Pending authority transfer already in progress" },
    { code: 6009, name: "NoPendingTransfer", msg: "No pending authority transfer" },
    { code: 6010, name: "WrongPendingAuthority", msg: "Caller is not the pending new authority" },
  ],
  types: [
    {
      name: "InitializeParams",
      type: {
        kind: "struct",
        fields: [
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "uri", type: "string" },
          { name: "decimals", type: "u8" },
          { name: "enablePermanentDelegate", type: "bool" },
          { name: "enableTransferHook", type: "bool" },
          { name: "defaultAccountFrozen", type: "bool" },
          { name: "transferHookProgramId", type: { option: "publicKey" } },
        ],
      },
    },
  ],
};
